Add record_dimension_timestream Functionality
swxsoc/swxsoc pull request #15
Opened 2024-09-25 10:30 UTC by dbarrous

### Overview
This pull request introduces the record_dimension_timestream function, which allows users to record measures and associated dimensions in an AWS Timestream database. This enhancement facilitates effective data logging and analysis by enabling the capture of various metrics tied to specific instruments and dimensions.

### Key Features
- Dimension Recording: Users can log multiple dimensions with their corresponding values, making data retrieval and analysis more contextual.
- Flexible Measurement Logging: Supports various measurement types and allows for custom measure names and values.
- Timestamp Handling: Automatically assigns timestamps to logged records, ensuring accurate tracking of when data was recorded.

### Also included in this PR:
- Tests which tests the recording with mock a mock aws account thanks to moto
- A User Guide docs page with an example on how to use it

2024-09-25 14:54 UTC, Alrobbertz approved these changes

2024-09-25 16:22 UTC, ehsteve requested changes

2024-10-03 18:08 UTC, ehsteve commented
@Alrobbertz and @dbarrous I'll work on integrating TimeSeries support here.

2024-10-04 01:05 UTC, ehsteve commented
@dbarrous not sure that i can finish this because i can't run this on my machine. Could you help? Also, would be good to add a guide on how to add credentials? I was surprised to see that even for the mock_aws you need credentials installed :(

2024-10-04 12:33 UTC, dbarrous commented on docs/user-guide/recording_to_timestream.rst
> +Before using the `~swxsoc.util.util.record_dimension_timestream` function, ensure that the following prerequisites are met:
Just to close the loop and resolve this comment, no credentials needed for the tests since it uses the moto library: https://pypi.org/project/moto/

2024-10-04 12:35 UTC, dbarrous commented
> @dbarrous not sure that i can finish this because i can't run this on my machine. Could you help? Also, would be good to add a guide on how to add credentials? I was surprised to see that even for the mock_aws you need credentials installed :(

To bring the conversation we had in slack here, no credentials needed if using the `@mock_aws` decorator around a test function. I have gone ahead and created a fixture that is used throughout to clean up the tests as well.

2024-10-04 17:47 UTC, ehsteve approved these changes
Looks great! Thanks for fixing the tests for me!

2024-10-04 17:47 UTC, merged